### ISSUE TITLE
let the user enter custom goals and save them in a database

### ISSUE THREAD

**Issue by jensdreske** [jensdreske/capstone-project#13]
# share your own goals

As a user I want to enter my own goals. 
If i find some information I'd like to add it to my goals for this game and share it with others or benefit from other user's research.

## acceptance criteria

- goals should persist
- goals can be added to my own custom goals
- goals can be shared with other users

## complexity 

M

## Tasks
- [x] set up form
- [x] include goals in calculation
- [x] implement local storage
- [x] store shared goals in a mongoDB
- [x] make shared goals accessible
