### ISSUE TITLE
add custom food items

### ISSUE THREAD

**Issue by jensdreske** [jensdreske/capstone-project#7]
###tasks
- [ ] add "add" button to food basket
- [ ] database with custom food items
- [ ] calculate shipping emissions based on distance and vehicle (✈️ 🚂 🚗)
- [ ] find API / database with co2/kg food
- [ ] image upload / choose icon (🌽 🍖)
